# Generated by Django 5.1.7 on 2025-04-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='person',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
