# Generated by Django 5.1.7 on 2025-04-06 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_offer_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='person',
        ),
        migrations.AddField(
            model_name='offer',
            name='person',
            field=models.ManyToManyField(related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
