# Generated by Django 5.1.6 on 2025-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_billinghistory_billinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='expiry',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='encrypted_card_number',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='encrypted_cvv',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='encrypted_expiry',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BillingHistory',
        ),
    ]
