# Generated by Django 5.1.7 on 2025-04-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_offer_person_offer_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='person',
        ),
    ]
