# Generated by Django 5.1.6 on 2025-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_paid_billinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
