# Generated by Django 5.1.7 on 2025-04-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_offer_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='people',
        ),
        migrations.AddField(
            model_name='offer',
            name='people',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
