# Generated by Django 5.1.6 on 2025-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='stripe_invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='encrypted_card_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='encrypted_cvv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='encrypted_expiry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
