# Generated by Django 5.1.7 on 2025-04-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_offer_people_offer_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rqoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=255)),
                ('name_company', models.CharField(max_length=255)),
                ('id_offer', models.CharField(max_length=100)),
            ],
        ),
    ]
