# Generated by Django 5.1.7 on 2025-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rqoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rqoffer',
            name='rp_offer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
