# Generated by Django 5.1.7 on 2025-04-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rqoffer_rp_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='people',
        ),
    ]
