# Generated by Django 5.1.6 on 2025-04-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_billinghistory_stripe_invoice_url_and_more'),
        ('accounts', '0010_alter_rqoffer_rp_offer'),
    ]

    operations = [
    ]
