# Generated by Django 5.1.7 on 2025-04-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_rqoffer_rp_offer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rqoffer',
            unique_together={},
        ),
    ]
