# Generated by Django 5.1.7 on 2025-04-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_rqoffer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rqoffer',
            unique_together=set(),
        ),
    ]
