# Generated by Django 5.1.7 on 2025-04-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_rqoffer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rqoffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rqoffer')),
            ],
        ),
    ]
