# Generated by Django 5.1.6 on 2025-04-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_chatmessage_rqoffer_unique_person_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rqoffer',
            name='chat_closed',
            field=models.BooleanField(default=False),
        ),
    ]
