# Generated by Django 5.1.7 on 2025-04-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_anothermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherModel',
        ),
    ]
