# Generated by Django 5.1.7 on 2025-04-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_billinghistory_stripe_invoice_url_and_more'),
        ('accounts', '0015_communitymessage_rqoffer_unique_person_offer'),
    ]

    operations = [
    ]
