# Generated by Django 5.1.6 on 2025-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_chatstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
