# Generated by Django 5.1.6 on 2025-04-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_billinghistory_created_at_and_more'),
        ('accounts', '0016_merge_20250419_1516'),
    ]

    operations = [
    ]
