# Generated by Django 5.1.7 on 2025-04-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_message_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
