# Generated by Django 5.1.7 on 2025-04-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('art', 'Art'), ('tech', 'Tech'), ('music', 'Music'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
