# Generated by Django 5.1.6 on 2025-04-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20250420_2301'),
        ('accounts', '0023_reply'),
    ]

    operations = [
    ]
