# Generated by Django 5.1.6 on 2025-05-06 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_onesignalplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rqoffer',
            name='offer',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='accounts.offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rqoffer',
            name='user',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
