# Generated by Django 5.1.6 on 2025-05-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rqoffer_offer_rqoffer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rqoffer',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='rqoffer',
            name='user',
        ),
    ]
