# Generated by Django 5.1.6 on 2025-05-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_is_2fa_enabled_user_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='hours',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
