# Generated by Django 5.1.6 on 2025-05-11 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_offer_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='company_name',
        ),
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
