# Generated by Django 5.1.6 on 2025-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_offer_company_name_offer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='company',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
