# Generated by Django 5.1.6 on 2025-05-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_offer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='company',
        ),
    ]
