# Generated by Django 5.1.6 on 2025-05-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_offer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='name_company',
            field=models.CharField(default='testCompanyName', max_length=255),
            preserve_default=False,
        ),
    ]
